---
title: "Cronograma"
toc: false
editor: source
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(gtExtras)
library(tidyverse)
gs4_deauth()
d <- read_sheet("1uQqlOXhSTnyb13cPlREb4d-6iLx9ilJPmvY0s6aiQOk")
```

```{r, echo = FALSE}
d %>% 
  select(-semana) %>% 
  mutate(
    fecha = as.Date(fecha),
    deadline = as.Date(deadline),
    consigna = ifelse(is.na(consigna), "", consigna),
    grupo = ifelse(is.na(grupo), "", grupo),
    material = ifelse(is.na(material), "", material)) %>%
  gt() %>%
  fmt_date(fecha, date_style = "10") %>%
  fmt_date(deadline, date_style = "10") %>%
  sub_missing(columns = fecha, missing_text = "") %>% 
  sub_missing(columns = deadline, missing_text = "") %>% 
  opt_row_striping(row_striping = FALSE) # %>% 
  # gt_highlight_rows(
  #    rows = 1:3,
  #    fill = "#ffffff",
  #    bold_target_only = TRUE
  #  ) %>%
  # gt_highlight_rows(
  #    rows = c(2,4,5),
  #    fill = "#edf8e9",
  #    bold_target_only = TRUE
  #  ) %>%
  # gt_highlight_rows(
  #    rows = 6:8,
  #    fill = "#c7e9c0",
  #    bold_target_only = TRUE
  #  ) %>%
  # gt_highlight_rows(
  #    rows = 9:11,
  #    fill = "#a1d99b",
  #    bold_target_only = TRUE
  #  ) %>%
  # gt_highlight_rows(
  #    rows = 12:14,
  #    fill = "#74c476",
  #    bold_target_only = TRUE
  #  ) %>%
  # gt_highlight_rows(
  #    rows = 15:16,
  #    fill = "#31a354",
  #    bold_target_only = TRUE
  #  )
```
